[workspace]
members = ["projects/*"]
default-members = [
    "projects/lady-saying",
    "projects/web-saying",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
